<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">

<!-- xacro arguments -->
<xacro:property name="width" value="0.1" />
<xacro:property name="bodylen" value="0.18" />

<!-- xacro macros -->
<xacro:macro name="default_origin">
   <origin rpy="1.57075 0 0" xyz="0 0 0"/>
</xacro:macro>

<xacro:macro name="wheel_create" params="prefix x y z">
	<link name="${prefix}_wheel">
		<visual>
			<xacro:default_origin />
			<geometry>
				<cylinder length="${bodylen/9}" radius="${width/4}"/>
			</geometry>
			<material name="black"/>
		</visual>
		<collision>
			<xacro:default_origin />
			<geometry>
				<cylinder length="${bodylen/9}" radius="${width/4}"/>
			</geometry>
		</collision>
		<inertial>
			<mass value="0.1"/>
			<inertia ixx="0.0005" ixy="0.0" ixz="0.0" iyy="0.0005" iyz="0.0" izz="0.0005"/>
		</inertial>
	</link>

	<joint name="${prefix}_joint" type="continuous">
		<axis rpy="0 0 0" xyz="0 1 0"/>
		<parent link="base_link"/>
		<child link="${prefix}_wheel"/>
		<origin rpy="0 0 0" xyz="${x} ${y} ${z}"/>
	</joint>

	<gazebo reference="${prefix}_wheel">
      <mu1 value="200.0"/>
      <mu2 value="100.0"/>
      <kp value="10000000.0" />
      <kd value="1.0" />
      <material>Gazebo/Black</material>
	</gazebo>
</xacro:macro>

<!-- color -->
<material name="blue">
	<color rgba="0 0 0.8 1"/>
</material>
<material name="black">
	<color rgba="0 0 0 1"/>
</material>
<material name="white">
	<color rgba="1 1 1 1"/>
</material>

<!-- base -->
<link name="base_link">
	<visual>
		<geometry>
			<box size="${bodylen} ${width} ${bodylen/2}"/>
		</geometry>
	</visual>
	<collision>
		<geometry>
			<box size="${bodylen} ${width} ${bodylen/2}"/>
		</geometry>
	</collision>
	<inertial>
    	<mass value="1.5"/>
    	<inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
	</inertial>	
</link>

<!-- wheels -->
<xacro:wheel_create prefix="right_front" x="0.05" y="-0.06" z="-0.03" />
<xacro:wheel_create prefix="right_back" x="-0.05" y="-0.06" z="-0.03" />
<xacro:wheel_create prefix="left_front" x="0.05" y="0.06" z="-0.03" />
<xacro:wheel_create prefix="left_back" x="-0.05" y="0.06" z="-0.03" />

<!-- gazebo -->
<xacro:include filename="robot.gazebo.xacro" />

</robot>